import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#e3e1e9',
        'inverse-surface': '#e3e1e9',
        'secondary-fixed-dim': '#7bd0ff',
        'on-secondary-fixed': '#001e2c',
        secondary: '#7bd0ff',
        'surface-container-lowest': '#0d0e13',
        'on-tertiary': '#472a00',
        'tertiary-container': '#ffbc68',
        'outline-variant': '#3b4a41',
        tertiary: '#ffe0be',
        'on-secondary': '#00354a',
        'on-tertiary-container': '#774a00',
        'surface-tint': '#00e297',
        'secondary-container': '#00a6e0',
        'on-error': '#690005',
        error: '#ffb4ab',
        'on-primary-fixed': '#002112',
        'on-primary-fixed-variant': '#005234',
        'inverse-on-surface': '#2f3036',
        'on-surface-variant': '#bacbbe',
        'surface-container-highest': '#34343a',
        'on-secondary-fixed-variant': '#004c69',
        'surface-bright': '#38393f',
        'primary-container': '#00e599',
        'primary-fixed-dim': '#00e297',
        'on-primary': '#003822',
        outline: '#849589',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#c4e7ff',
        'on-primary-container': '#00613e',
        surface: '#121318',
        'surface-dim': '#121318',
        background: '#121318',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container': '#1e1f25',
        'surface-container-low': '#1a1b21',
        'on-secondary-container': '#00374d',
        'error-container': '#93000a',
        'surface-variant': '#34343a',
        'tertiary-fixed-dim': '#ffb95f',
        primary: '#6dffba',
        'surface-container-high': '#292a2f',
        'inverse-primary': '#006c46',
        'primary-fixed': '#4dffb2',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-fixed': '#2a1700',
        'on-surface': '#e3e1e9',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'space-lg': '24px',
        'space-4xl': '96px',
        'space-xs': '8px',
        'space-3xl': '64px',
        'space-md': '16px',
        'gutter-desktop': '24px',
        'space-2xl': '48px',
        'space-xl': '32px',
        'space-2xs': '4px',
        'space-sm': '12px',
        'grid-unit': '4px',
        'gutter-mobile': '16px',
      },
      fontFamily: {
        'display-hero': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'mono-code': ['JetBrains Mono', 'monospace'],
        'body-md': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'mono-label': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'display-hero-mobile': ['Space Grotesk', 'sans-serif'],
        'mono-badge': ['JetBrains Mono', 'monospace'],
        'headline-xl-mobile': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Space Grotesk', 'sans-serif'],
        'headline-xl': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'mono-code': ['13px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'mono-label': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'mono-badge': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        ping: {
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'gradient-x': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'border-glow': {
          '0%, 100%': { borderColor: 'rgba(109,255,186,0.3)' },
          '50%': { borderColor: 'rgba(109,255,186,0.8)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
        'fade-in': 'fade-in 0.4s ease-out forwards',
        ping: 'ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite',
        'slide-in-right': 'slide-in-right 0.7s ease-out forwards',
        'gradient-x': 'gradient-x 4s ease infinite',
        'border-glow': 'border-glow 2s ease-in-out infinite',
        float: 'float 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

export default config
